== simple alert domain specific language 

This tiny project contains a simple DSL (internal) written in Scala language, so that it can be run on top of JVM.

== Dependencies

--
. Java
. link:http://www.scala-lang.org/download/[Scala]
. link:http://www.scala-sbt.org/release/docs/Getting-Started/Setup.html[Sbt]
--

== Usage
For running the prepared demo App all is needed is:

 $ sbt run

This will define three simple alerts on your platform resource (assumes id +10001+). It assumes the RHQ server to be running. For interactive mode just type:

 $ sbt console

== Examples

[source,scala,numbered]
  val alert1 =
    define alert having {
      name -> "foo"
      description -> "test"
      priority -> HIGH
      enabled -> true

      conditions all(
        CONFIG CHANGED,
        AVAILABILITY STAYS DOWN FOR 1 HOUR
        )
      dampening -> (2 from 4 last evaluations)
    }

  val alert2 =
    define alert having {
      name -> "bar"
      priority -> LOW
      enabled -> false

      conditions any (
        AVAILABILITY GOES DOWN
        )

      dampening -> (2 consecutive evaluations)
    }

  val alert3 =
    define alert having {
      name -> "baz"

      conditions any(
        "viewProcessList" OPERATION HAS STATUS FAILURE,
        AVAILABILITY STAYS DOWN FOR 42 MINUTES
        )
      dampening -> (in last 25 minutes 3 times)
    }


  // create the alerts on the RHQ server using POST method on REST endpoint
  val futureAlert1: Future[Response] = server create alert1 on resource withId 10001
  val futureAlert2: Future[Response] = server create alert2 on resource withId 10001

  // the default hostname and credentials can be changed
  val futureAlert3 = server withHostName("http://localhost:7080") withCredentials("rhqAdmin", "rhqAdmin") create alert3 on resource withId 10001
